// AI service — React NEVER runs ML models. It only:
//  1. reads AI results already stored in Firestore (candidate_windows,
//     maintenance_tasks priority fields, block_plans from CP-SAT), and
//  2. triggers the pipeline on the FastAPI backend when VITE_API_BASE_URL
//     is configured.
//
// Pipeline contract (see ML_pipeline/README.md):
//   Module1 RF (module1_rf_model.joblib): tasks -> {priority_score, risk_level}
//   Module2 XGBRanker (module2_xgb_ranker.joblib): candidates -> ranked windows
//   Module3 CP-SAT: ranked windows + constraints -> final block_plans
// The backend owns this chain; the portal only displays stored outcomes.

export const API_BASE = import.meta.env.VITE_API_BASE_URL || ''
export const isBackendConfigured = Boolean(API_BASE)

// Ping GET /api/health (short timeout so the page never hangs).
export async function backendHealth(timeoutMs = 5000) {
  if (!isBackendConfigured) return { ok: false, reason: 'not-configured' }
  const ctrl = new AbortController()
  const t = setTimeout(() => ctrl.abort(), timeoutMs)
  try {
    const res = await fetch(`${API_BASE}/api/health`, { signal: ctrl.signal })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const data = await res.json()
    return { ok: data.models_loaded === true, ...data }
  } catch (e) {
    return { ok: false, reason: e.name === 'AbortError' ? 'timeout' : (e.message || 'unreachable') }
  } finally {
    clearTimeout(t)
  }
}

async function post(path, body) {
  const res = await fetch(`${API_BASE}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })
  if (!res.ok) throw new Error(`Backend HTTP ${res.status}`)
  return res.json()
}

import { addRecord, updateDocFields, createPlanVersion, writeAudit } from './firestoreService.js'

// Ask the backend to run the full chain for the given tasks.
// Expected backend routes (FastAPI): /api/pipeline/run  (or the
// finer-grained /api/module1/prioritize, /api/module2/rank-windows,
// /api/module3/optimize).
export async function runPipeline(taskIds = [], clientContext = {}) {
  if (!isBackendConfigured) throw new Error('AI backend is not configured. Set VITE_API_BASE_URL to your FastAPI server.')
  const body = {
    task_ids: taskIds,
    tasks: clientContext.tasks || [],
    assets: clientContext.assets || [],
    corridor_blocks: clientContext.corridor_blocks || [],
    weather: clientContext.weather || [],
    goods_forecasts: clientContext.goods_forecasts || [],
    candidate_windows: clientContext.candidate_windows || [],
    block_plans: clientContext.block_plans || [],
  }
  const res = await post('/api/pipeline/run', body)

  // If backend executed in hybrid mode (returning client_payload for client to persist):
  if (res?.client_payload && res.persisted_by === 'client') {
    const cp = res.client_payload
    // 1. Update maintenance tasks with Module 1 scores and scheduled status
    if (Array.isArray(cp.tasks_patch)) {
      for (const t of cp.tasks_patch) {
        if (t.doc_id) {
          const patch = {
            priority_score: t.priority_score,
            risk_level: t.risk_level,
            ai_scored_at: t.ai_scored_at,
            ai_run_id: t.ai_run_id,
            ai_assumptions: t.ai_assumptions,
          }
          if (t.status) patch.status = t.status
          if (t.block_plan_id) patch.block_plan_id = t.block_plan_id
          if (t.plan_id) patch.plan_id = t.plan_id
          if (t.ai_scheduled_at) patch.ai_scheduled_at = t.ai_scheduled_at
          await updateDocFields('maintenance_tasks', t.doc_id, patch).catch((e) => console.warn('[aiService] Failed task patch:', e.message))
        }
      }
    }
    // 2. Add candidate windows
    if (Array.isArray(cp.candidate_windows)) {
      for (const w of cp.candidate_windows) {
        await addRecord('candidate_windows', w).catch((e) => console.warn('[aiService] Failed window add:', e.message))
      }
    }
    // 3. Add block plans & plan versions
    if (Array.isArray(cp.plans)) {
      for (const p of cp.plans) {
        const planDocId = await addRecord('block_plans', p).catch((e) => console.warn('[aiService] Failed plan add:', e.message))
        if (planDocId) {
          await createPlanVersion({
            plan_id: p.plan_id,
            version: '1.0',
            reason: 'Generated by CP-SAT solver',
            schedule_snapshot: p,
            created_by: 'ai-pipeline',
            status: 'pending_approval',
          }).catch((e) => console.warn('[aiService] Failed version add:', e.message))
        }
      }
    }
    await writeAudit({
      user_email: 'ai-pipeline',
      action: 'pipeline_run',
      entity_type: 'pipeline',
      entity_id: res.run_id,
      prev_status: '',
      new_status: 'completed',
      details: `AI pipeline run ${res.run_id} executed and saved to Firestore.`,
    }).catch(() => {})
  }

  return res
}

export async function prioritizeTasks(tasks) {
  if (!isBackendConfigured) throw new Error('AI backend is not configured.')
  return post('/api/module1/prioritize', { tasks })
}

export async function rankWindows(candidates) {
  if (!isBackendConfigured) throw new Error('AI backend is not configured.')
  return post('/api/module2/rank-windows', { candidates })
}
